services:
  php:
    image: php:8.2-fpm
    container_name: ddd_company_php
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:cached
    build:
      context: .
      dockerfile: docker/php/Dockerfile
  nginx:
    image: nginx:alpine
    container_name: ddd_company_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  db:
    image: mariadb:10.7
    container_name: ddd_company_db
    environment:
      - MARIADB_ROOT_PASSWORD=secret
      - MARIADB_DATABASE=ddd_company
      - MARIADB_USER=ddd_user
      - MARIADB_PASSWORD=ddd_pass
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

